"""add workflow user relation

Revision ID: 97d2e37960ff
Revises: b5326e73697b
Create Date: 2026-08-08 12:01:16.723360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d2e37960ff'
down_revision: Union[str, Sequence[str], None] = 'b5326e73697b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'user_id')
    # ### end Alembic commands ###
